# Copyright 2020-present, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
best_args = {'seq-cifar10': {'sgd': {-1: {'lr': 0.1,
                                          'batch_size': 32,
                                          'n_epochs': 50}},
                             'joint': {-1: {'lr': 0.1,
                                            'batch_size': 32,
                                            'n_epochs': 50}},
                             'er': {200: {'lr': 0.1,
                                          'minibatch_size': 32,
                                          'batch_size': 32,
                                          'n_epochs': 50},
                                    500: {'lr': 0.1,
                                          'minibatch_size': 32,
                                          'batch_size': 32,
                                          'n_epochs': 50},
                                    1000: {'lr': 0.03,
                                           'minibatch_size': 32,
                                           'batch_size': 32,
                                           'n_epochs': 50}},
                             'er_tricks': {200: {'lr': 0.1,
                                                 'minibatch_size': 32,
                                                 'batch_size': 32,
                                                 'n_epochs': 50,
                                                 'bic_epochs': 50,
                                                 'elrd': 0.99999935},
                                           500: {'lr': 0.03,
                                                 'minibatch_size': 32,
                                                 'batch_size': 32,
                                                 'n_epochs': 50,
                                                 'bic_epochs': 50,
                                                 'elrd': 0.99999935},
                                           1000: {'lr': 0.03,
                                                  'minibatch_size': 32,
                                                  'batch_size': 32,
                                                  'n_epochs': 50,
                                                  'bic_epochs': 50,
                                                  'elrd': 0.99999935}},
                             'gem': {200: {'lr': 0.03,
                                           'gamma': 0.5,
                                           'batch_size': 32,
                                           'n_epochs': 50,
                                           'iba': False},
                                     500: {'lr': 0.03, 'gamma': 0.5,
                                           'batch_size': 32,
                                           'n_epochs': 50,
                                           'iba': False},
                                     5120: {'lr': 0.03, 'gamma': 0.5,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                           'iba': False}},
                             'agem': {200: {'lr': 0.03,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                            'iba': False},
                                      500: {'lr': 0.03,
                                            'minibatch_size': 128,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                           'iba': False},
                                      5120: {'lr': 0.03,
                                             'minibatch_size': 128,
                                             'batch_size': 32,
                                             'n_epochs': 50,
                                           'iba': False}},
                             'hal': {200: {'lr': 0.03,
                                           'minibatch_size': 32,
                                           'batch_size': 32,
                                           'n_epochs': 50,
                                           'hal_lambda': 0.2,
                                           'beta': 0.5,
                                           'gamma': 0.1,
                                           'steps_on_anchors': 100,
                                           'finetuning_epochs': 1,
                                           'iba': False},
                                     500: {'lr': 0.03,
                                           'minibatch_size': 32,
                                           'batch_size': 32,
                                           'n_epochs': 50,
                                           'hal_lambda': 0.1,
                                           'beta': 0.3,
                                           'gamma': 0.1,
                                           'steps_on_anchors': 100,
                                           'finetuning_epochs': 1,
                                           'iba': False},
                                     1000: {'lr': 0.03,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                            'hal_lambda': 0.1,
                                            'beta': 0.3,
                                            'gamma': 0.1,
                                            'steps_on_anchors': 100,
                                            'finetuning_epochs': 1,
                                           'iba': False}},
                             'icarl': {200: {'lr': 0.1,
                                             'minibatch_size': 0,
                                             'softmax_temp': 2.0,
                                             'wd_reg': 0.00001,
                                             'batch_size': 32,
                                             'n_epochs': 50},
                                       500: {'lr': 0.1,
                                             'minibatch_size': 0,
                                             'softmax_temp': 2.0,
                                             'wd_reg': 0.00001,
                                             'batch_size': 32,
                                             'n_epochs': 50},
                                       5120: {'lr': 0.03,
                                              'minibatch_size': 0,
                                              'softmax_temp': 2.0,
                                              'wd_reg': 0.00001,
                                              'batch_size': 32,
                                              'n_epochs': 50}}},
             'seq-fmnist': {'sgd': {-1: {'lr': 0.2,
                                         'batch_size': 10,
                                         'n_epochs': 1}},
                            'joint': {-1: {'lr': 0.2,
                                           'batch_size': 10,
                                           'n_epochs': 1}},
                            'er': {200: {'lr': 0.03,
                                         'minibatch_size': 128,
                                         'batch_size': 10,
                                         'n_epochs': 1},
                                   500: {'lr': 0.1,
                                         'minibatch_size': 128,
                                         'batch_size': 10,
                                         'n_epochs': 1},
                                   1000: {'lr': 0.1,
                                          'minibatch_size': 128,
                                          'batch_size': 10,
                                          'n_epochs': 1}},
                            'er_tricks': {200: {'lr': 0.03,
                                                'minibatch_size': 32,
                                                'batch_size': 10,
                                                'n_epochs': 1,
                                                'bic_epochs': 50,
                                                'elrd': 0.99995},
                                          500: {'lr': 0.03,
                                                'minibatch_size': 32,
                                                'batch_size': 10,
                                                'n_epochs': 1,
                                                'bic_epochs': 50,
                                                'elrd': 0.99995},
                                          1000: {'lr': 0.1,
                                                 'minibatch_size': 32,
                                                 'batch_size': 10,
                                                 'n_epochs': 1,
                                                 'bic_epochs': 50,
                                                 'elrd': 0.99995}},
                            'gem': {200: {'lr': 0.03,
                                          'gamma': 1,
                                          'batch_size': 10,
                                          'n_epochs': 1,
                                           'iba': False},
                                    500: {'lr': 0.03,
                                           'gamma': 1,
                                           'batch_size': 10,
                                           'n_epochs': 1,
                                           'iba': False},
                                    1000: {'lr': 0.03,
                                            'gamma': 1,
                                            'batch_size': 10,
                                            'n_epochs': 1,
                                           'iba': False}},
                            'agem': {200: {'lr': 0.03,
                                           'minibatch_size': 128,
                                           'batch_size': 10,
                                           'n_epochs': 1,
                                           'iba': False},
                                     500: {'lr': 0.03,
                                           'minibatch_size': 128,
                                           'batch_size': 10,
                                           'n_epochs': 1,
                                           'iba': False},
                                     1000: {'lr': 0.03,
                                           'minibatch_size': 128,
                                            'batch_size': 10,
                                            'n_epochs': 1,
                                            'iba': False}},
                            'hal': {200: {'lr': 0.03,
                                          'minibatch_size': 32,
                                          'batch_size': 10,
                                          'n_epochs': 1,
                                          'hal_lambda': 0.1,
                                          'beta': 0.5,
                                          'gamma': 0.1,
                                          'steps_on_anchors': 100,
                                          'finetuning_epochs': 1,
                                           'iba': False},
                                    500: {'lr': 0.03,
                                          'minibatch_size': 128,
                                          'batch_size': 10,
                                          'n_epochs': 1,
                                          'hal_lambda': 0.1,
                                          'beta': 0.5,
                                          'gamma': 0.1,
                                          'steps_on_anchors': 100,
                                          'finetuning_epochs': 1,
                                           'iba': False},
                                    1000: {'lr': 0.03,
                                           'minibatch_size': 128,
                                           'batch_size': 10,
                                           'n_epochs': 1,
                                           'hal_lambda': 0.3,
                                           'beta': 0.5,
                                           'gamma': 0.1,
                                           'steps_on_anchors': 100,
                                           'finetuning_epochs': 1,
                                           'iba': False}},
                            'icarl': {200: {'lr': 0.1,
                                            'minibatch_size': 32,
                                            'softmax_temp': 2.0,
                                            'wd_reg': 0.0005,
                                            'batch_size': 10,
                                            'n_epochs': 1},
                                      500: {'lr': 0.03,
                                            'minibatch_size': 32,
                                            'softmax_temp': 2.0,
                                            'wd_reg': 0.0005,
                                            'batch_size': 10,
                                            'n_epochs': 1},
                                      1000: {'lr': 0.1,
                                             'minibatch_size': 128,
                                             'softmax_temp': 2.0,
                                             'wd_reg': 0.0005,
                                             'batch_size': 10,
                                             'n_epochs': 1}}},
             'seq-core50': {'sgd': {-1: {'lr': 0.1,
                                         'batch_size': 32,
                                         'n_epochs': 15}},
                            'joint': {-1: {'lr': 0.1,
                                           'batch_size': 32,
                                           'n_epochs': 15}},
                            'er': {200: {'lr': 0.03,
                                         'minibatch_size': 32,
                                         'batch_size': 32,
                                         'n_epochs': 15},
                                   500: {'lr': 0.03,
                                         'minibatch_size': 32,
                                         'batch_size': 32,
                                         'n_epochs': 15},
                                   1000: {'lr': 0.03,
                                          'minibatch_size': 32,
                                          'batch_size': 32,
                                          'n_epochs': 15}},
                            'er_tricks': {200: {'lr': 0.03,
                                                'minibatch_size': 32,
                                                'batch_size': 32,
                                                'n_epochs': 15,
                                                'bic_epochs': 15,
                                                'elrd': 0.9999993},
                                          500: {'lr': 0.03,
                                                'minibatch_size': 32,
                                                'batch_size': 32,
                                                'n_epochs': 15,
                                                'bic_epochs': 15,
                                                'elrd': 0.9999993},
                                          1000: {'lr': 0.03,
                                                 'minibatch_size': 32,
                                                 'batch_size': 32,
                                                 'n_epochs': 15,
                                                 'bic_epochs': 15,
                                                 'elrd': 0.9999993}},
                            'hal': {200: {'lr': 0.03,
                                          'minibatch_size': 128,
                                          'batch_size': 32,
                                          'n_epochs': 15,
                                          'hal_lambda': 0.1,
                                          'beta': 0.5,
                                          'gamma': 0.1,
                                          'steps_on_anchors': 100,
                                          'finetuning_epochs': 1,
                                           'iba': False},
                                    500: {'lr': 0.03,
                                          'minibatch_size': 128,
                                          'batch_size': 32,
                                          'n_epochs': 15,
                                          'hal_lambda': 0.1,
                                          'beta': 0.5,
                                          'gamma': 0.1,
                                          'steps_on_anchors': 100,
                                          'finetuning_epochs': 1,
                                           'iba': False},
                                    1000: {'lr': 0.03,
                                           'minibatch_size': 128,
                                           'batch_size': 32,
                                           'n_epochs': 15,
                                           'hal_lambda': 0.1,
                                           'beta': 0.5,
                                           'gamma': 0.1,
                                           'steps_on_anchors': 100,
                                           'finetuning_epochs': 1,
                                           'iba': False}},
                            'agem': {200: {'lr': 0.1,
                                           'minibatch_size': 32,
                                           'batch_size': 32,
                                           'n_epochs': 15,
                                           'iba': False},
                                     500: {'lr': 0.1,
                                           'minibatch_size': 32,
                                           'batch_size': 32,
                                           'n_epochs': 15,
                                           'iba': False},
                                     1000: {'lr': 0.03,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 15,
                                           'iba': False}},
                            'icarl': {200: {'lr': 0.2,
                                            'wd_reg': 0,
                                            'batch_size': 32,
                                            'n_epochs': 15},
                                      500: {'lr': 0.2,
                                            'wd_reg': 0,
                                            'batch_size': 32,
                                            'n_epochs': 15},
                                      1000: {'lr': 0.2,
                                             'wd_reg': 0,
                                             'batch_size': 32,
                                             'n_epochs': 15}}},
             'seq-cifar100': {'sgd': {-1: {'lr': 0.1,
                                           'batch_size': 32,
                                           'n_epochs': 50}},
                              'joint': {-1: {'lr': 0.1,
                                             'batch_size': 32,
                                             'n_epochs': 50}},
                              'er': {200: {'lr': 0.1,
                                           'minibatch_size': 32,
                                           'batch_size': 32,
                                           'n_epochs': 50},
                                     500: {'lr': 0.1,
                                           'minibatch_size': 32,
                                           'batch_size': 32,
                                           'n_epochs': 50},
                                     1000: {'lr': 0.1,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 50}},
                              'er_tricks': {200: {'lr': 0.03,
                                                  'minibatch_size': 32,
                                                  'batch_size': 32,
                                                  'n_epochs': 50,
                                                  'bic_epochs': 50,
                                                  'elrd': 0.99999927},
                                            500: {'lr': 0.03,
                                                  'minibatch_size': 32,
                                                  'batch_size': 32,
                                                  'n_epochs': 50,
                                                  'bic_epochs': 50,
                                                  'elrd': 0.99999927},
                                            1000: {'lr': 0.03,
                                                   'minibatch_size': 32,
                                                   'batch_size': 32,
                                                   'n_epochs': 50,
                                                   'bic_epochs': 50,
                                                   'elrd': 0.99999927}},
                              'hal': {200: {'lr': 0.1,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 1,
                                            'hal_lambda': 0.1,
                                            'beta': 0.3,
                                            'gamma': 0.1,
                                            'steps_on_anchors': 100,
                                            'finetuning_epochs': 1,
                                           'iba': False},
                                      500: {'lr': 0.1,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                            'hal_lambda': 0.1,
                                            'beta': 0.3,
                                            'gamma': 0.1,
                                            'steps_on_anchors': 100,
                                            'finetuning_epochs': 1,
                                           'iba': False},
                                      1000: {'lr': 0.1,
                                             'minibatch_size': 32,
                                             'batch_size': 32,
                                             'n_epochs': 50,
                                             'hal_lambda': 0.1,
                                             'beta': 0.3,
                                             'gamma': 0.1,
                                             'steps_on_anchors': 100,
                                             'finetuning_epochs': 1,
                                           'iba': False}},
                              'gem': {200: {'lr': 0.03,
                                            'gamma': 0.5,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                           'iba': False},
                                      500: {'lr': 0.03,
                                            'gamma': 0.5,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                           'iba': False},
                                      1000: {'lr': 0.03,
                                            'gamma': 0.5,
                                            'batch_size': 32,
                                            'n_epochs': 50,
                                           'iba': False}},
                              'agem': {200: {'lr': 0.03,
                                             'minibatch_size': 128,
                                             'batch_size': 32,
                                             'n_epochs': 50,
                                           'iba': False},
                                       500: {'lr': 0.03,
                                             'minibatch_size': 128,
                                             'batch_size': 32,
                                             'n_epochs': 50,
                                           'iba': False},
                                       1000: {'lr': 0.03,
                                              'minibatch_size': 128,
                                              'batch_size': 32,
                                              'n_epochs': 50,
                                           'iba': False}},
                              'icarl': {200: {'lr': 0.1,
                                              'minibatch_size': 0,
                                              'softmax_temp': 2.0,
                                              'wd_reg': 0.00001,
                                              'batch_size': 32,
                                              'n_epochs': 50},
                                        500: {'lr': 0.1,
                                              'minibatch_size': 0,
                                              'softmax_temp': 2.0,
                                              'wd_reg': 0.00001,
                                              'batch_size': 32,
                                              'n_epochs': 50},
                                        5120: {'lr': 0.03,
                                               'minibatch_size': 0,
                                               'softmax_temp': 2.0,
                                               'wd_reg': 0.00001,
                                               'batch_size': 32,
                                               'n_epochs': 50}}},
             }
